[frontend]
frontend-vm ansible_host=52.172.94.142

[backend]
backend-vm ansible_host=20.41.223.95 backend_private_ip=10.0.2.4

[all:vars]
ansible_user=saima
ansible_python_interpreter=/usr/bin/python3

[backend:vars]
backend_app_port=8080
mysql_host=epicbookmysql6992.mysql.database.azure.com
mysql_port=3306
mysql_database=bookstore
