---
- name: Configure EpicBook backend
  hosts: backend
  become: true
  roles:
    - common
    - backend
    - database

  tasks:
    - name: Start EpicBook after database initialization
      ansible.builtin.systemd:
        name: epicbook
        state: started

    - name: Verify EpicBook backend
      ansible.builtin.include_role:
        name: verification


- name: Configure EpicBook frontend
  hosts: frontend
  become: true
  roles:
    - common
    - frontend

  tasks:
    - name: Verify EpicBook frontend
      ansible.builtin.include_role:
        name: verification
